[package]
name = "epsilon"
version = "0.3.0"
edition = "2021"

description = "Fast autograd using dual numbers"
authors = ["loovjo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"
